$yaml = @'
name: Build and Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TailwindCSS (runner-local)
        run: |
          npm init -y
          npm install -D tailwindcss postcss autoprefixer
          npx tailwindcss -v

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
'@

# Ensure folder exists and write the file (UTF8, no extra BOM handling here)
New-Item -ItemType Directory -Force -Path .github\workflows | Out-Null
$yaml | Out-File -FilePath .github\workflows\deploy.yml -Encoding utf8
Write-Host "WROTE: .github\workflows\deploy.yml"
